### ISSUE TITLE
Add precompute runtime optimizations

### ISSUE THREAD

**Issue by AddressXception** [microsoft/electionguard-python#397] opened 2021-07-26 13:27 UTC
## Feature Request

**Description**
As a user of the library i would like to precompute data tables used in ballot encryption and decryption that do not rely on sensitive data such as the nonces so that i can optimize the real-time perceived performance when executing encryption and decryption operations

specifically, a number of the exponentiations calculated whne encrypting a ballot are not associated with the nonce's and therefore can be precomputed in a lookup table.

similarly the discrete log lookup table used when decrypting is currently precomputed using a global cache and async function calls.

The implementation should use a consistent and reproducable pattern similar to other segments of the code which follow a functional pattern at the lowest level and include a convenience wrapper that can manage objects and global state.

**Comment by keithrfung** [comment] 2021-09-09 22:28
I believe this is a duplicate of #410

**Closed by keithrfung** 2021-09-09 22:28 UTC
Labels: enhancement, code owner only
