### ISSUE TITLE
🐞 BigInts in constants.json are numbers but are strings in context.json

### ISSUE THREAD

**Issue by ramsdell** [microsoft/electionguard-python#524] opened 2022-01-21 18:55 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Big integers are represented as JSON numbers in constants.json, but as JSON strings that must be parsed into numbers in context.json.

### Expected Behavior

Please be consistent and pick one of the behaviors.

### Steps To Reproduce

Look at the JSON files.

### Environment

```markdown
- OS:
```

**Comment by keithrfung** [comment] 2022-01-24 17:01
This is currently a circular reference issue. The `BaseElement` which is used for all larger ints uses the `ElectionConstants` file. 

A simple solution is to export a different file like `ElectionConstantsRecord` to resolve this. I think in **ElectionGuard 2.0** we should rethink this dependency tree entirely.

**Comment by ramsdell** [comment] 2022-01-24 19:00
I looked carefully at all of the JSON files that make up an election record.  With the exception of constants.json, all of the files represent bignums as strings, not integers.  It would be better to export the constants using the same representation used in all the other files.  That way, the same JSON parser can be used for all of the JSON files.

**Comment by keithrfung** [comment] 2022-02-07 14:19
We ARE using the same JSON parser for Python, we are not using the same type. We're using pydantic which identifies those items as integers not bigints. In python, there is no difference. We have a class that is isolated to handle BigInts. 

Again, the issue is a circular reference. The big integer classes are currently all defined by being mod a large or a small prime. These constant files allow users to import the large or small prime that would define those big integer classes.

**Comment by JohnLCaron** [comment] 2022-02-13 23:07
On closer look, while I do see the quoted ElementMod vs unquoted BigInteger, my parser doesnt care. I was failing on the fact that the representation is now in base 10, before it was base 16.

Still need to nail this down in a formal spec.  I suppose base64 would be another possibility, for compactness.

**Comment by keithrfung** [comment] 2022-02-28 23:15
Closing this. See issue created to resolve this situation.

**Closed by keithrfung** 2022-02-28 23:15 UTC
Labels: bug, code owner only
